name: "Prettier Check & Fix"

on:
  push:
    branches: [master]
    paths:
      - '**/*.{js,md,yml,json,vue,scss}'
  pull_request:
    branches: [master]

jobs:
  # Job 1: Check formatting and annotate PRs (safe for forks)
  prettier-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Prettier check via npx
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx --yes prettier --check "**/*.{js,md,yml,json,vue,scss}" \
            | reviewdog -f=eslint -name="prettier" -reporter=github-pr-check || true

  # Job 2: Apply fixes and push (only runs on trusted pushes)
  prettier-fix:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply Prettier fixes via npx
        run: |
          npx --yes prettier --write "**/*.{js,md,yml,json,vue,scss}"
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "style: automated Prettier formatting"
            git push
          else
            echo "No formatting changes."
          fi
