name: "Prettier Check & Fix"

on:
  push:
    branches: [master]
    paths:
      - '**/*.{js,md,yml,json,vue,scss}'
  pull_request:
    branches: [master]

jobs:
  # Job 1: Run Prettier check + PR annotations (safe for forks/untrusted PRs)
  prettier-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read           # safe default
      pull-requests: write     # needed for reviewdog annotations

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Prettier & reviewdog
        run: |
          npm install --no-save prettier
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Prettier check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx prettier --check "**/*.{js,md,yml,json,vue,scss}" \
            | reviewdog -f=eslint -name="prettier" -reporter=github-pr-check || true

  # Job 2: Apply Prettier fixes & push (only runs on trusted push events)
  prettier-fix:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Prettier
        run: npm install --no-save prettier

      - name: Apply fixes & push
        run: |
          npx prettier --write "**/*.{js,md,yml,json,vue,scss}"
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "style: automated Prettier formatting"
            git push
          else
            echo "No formatting changes."
          fi
