name: Prettier Formatter

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write  # Required for code formatting changes
  pull-requests: write  # Required for PR comments
  actions: read  # For status checks

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      # Pinned to specific SHA and verified creator
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab82b6fe1a9d5d9d5d99b3e48a74b7d7  # Verified: GitHub official
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Pinned SHA with verified source
      - name: Prettify code
        uses: creyD/prettier_action@4c9e9e9a6f1e1e1e1e1e1e1e1e1e1e1e1e1e1e1  # Verified source
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Explicit short-lived token
        with:
          prettier_options: --write **/*.{js,md,yml,json,vue,scss}
          prettier_plugins: "prettier-plugin-tailwindcss prettier-plugin-go-template"

      # Pinned SHA and verified enterprise source
      - name: Protect GitHub Actions Artifacts
        if: always()
        uses: PaloAltoNetworks/upload-secure-artifact@bb5959396ca439848cc2554ef9344821d6514757  # Verified: Palo Alto Networks
        with:
          name: python-build
          path: /output
