name: Prettier Formatter

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b3d86c0f9c102a8dddc6504e690e6e  # Pinned SHA-1 for v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@526c0a475198449837738585a39c1fe81a55212f # Pinned SHA-1
        with:
          prettier_options: --write **/*.{js,md,yml,json,vue,scss}
          prettier_plugins: "prettier-plugin-tailwindcss prettier-plugin-go-template"
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Explicit short-lived token

      - name: Protect GitHub Actions Artifacts
        if: always()  # Run even if previous steps fail
        uses: PaloAltoNetworks/upload-secure-artifact@bb5959396ca439848cc2554ef9344821d6514757 # Pinned SHA-1
        with:
          name: python-build
          path: /output
