name: Prettier Check

on:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Prepare directory for results
        run: mkdir -p ./prettier-results

      - name: Dry-run Prettier
        run: |
          npx prettier --check "**/*.{js,md,yml,json,vue,scss}" \
            > ./prettier-results/output.txt || true

      - name: Archive results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: prettier-results
          path: ./prettier-results/
