name: Remove old artifacts

on:
  schedule:
    # At 00:00 on day-of-month 1
    - cron: '0 0 1 * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:  # Least-privilege permissions
      actions: write
      contents: read

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '1 month'
          # skip-tags: true  # Optional: Uncomment to preserve tagged artifacts
          # skip-recent: 5   # Optional: Uncomment to preserve recent artifacts

      - name: Protect GitHub Actions Artifacts
        uses: PaloAltoNetworks/upload-secure-artifact@v1.0.5  # Verified: Palo Alto Networks
        with:
          name: python-build
          path: /output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Short-lived token, masked in logs
