name: Remove old artifacts

on:
  schedule:
    # At 00:00 on day-of-month 1
    - cron: '0 0 1 * *'

permissions:
  contents: read

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write   # needed to delete artifacts
      contents: read

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@44fc7acaf1b3d0987da0e8d4707a989d80e9554b # v1.4.0
        with:
          age: '1 month'
          # skip-tags: true
          # skip-recent: 5

      - name: Protect GitHub Actions Artifacts
        uses: PaloAltoNetworks/upload-secure-artifact@5c3aaec37eb9b955a226b5fdb42573decf7e7876 # v1.0.5
        with:
          name: python-build
          path: /output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
